# Generated by Codex on 2026-05-27

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alt_text_app', '0002_imagedocument_thumbnail_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenRouterAltText',
            new_name='GeneratedAltText',
        ),
        migrations.RenameField(
            model_name='generatedalttext',
            old_name='openrouter_response_id',
            new_name='response_id',
        ),
        migrations.RenameField(
            model_name='generatedalttext',
            old_name='openrouter_created_at',
            new_name='response_created_at',
        ),
        migrations.AddField(
            model_name='generatedalttext',
            name='base_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='generatedalttext',
            name='model_server',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='generatedalttext',
            name='image_document',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='generated_alt_text',
                to='alt_text_app.imagedocument',
            ),
        ),
        migrations.AlterModelOptions(
            name='generatedalttext',
            options={
                'verbose_name': 'Generated Alt Text',
                'verbose_name_plural': 'Generated Alt Text',
            },
        ),
    ]
